<?php
	require('authenticate.php');   // authenticate for required login
    require('connect.php');        // connect to the database
    session_start();
    
    $redirect_javascript =  '<script type="text/javascript"> '.
                                'alert("Please log in/register to make changes."); '.
                                'window.location.href="login_signup.php"'.
                            '</script>';
    if(!isset($_SESSION['username'])) {
        echo $redirect_javascript;
    }

    // use the get superglobal to get the id number
    $id_num = $_GET['id'];

    // Delete and Select queries
    $select_blog  = "SELECT * FROM blogs WHERE id='{$id_num}' ";
    $delete_query = "DELETE FROM blogs WHERE id={$id_num} ";

    // Run the query
    $result = $db->query($select_blog);
    // Grab the values from the table
    while($row = $result->fetch_assoc()){
        $id = $row['id'];
        $title = $row['title'];
        $content = $row['content'];
        $datetime = $row['datetime'];
    }

    // Check for numericality of the id, redirect to index page
    if(!is_numeric($id_num)){
        header('Location: index.php');
    }

    // set date and time zones, grab today's date and store in $today
    // date_default_timezone_set("Canada/Central");
    $today = date('Y-m-d H:i:s');

    // set variable to contain a boolean value to be returned from the form
    $confirm_box = "confirm('Are you sure you wish to delete this post?')";

    // If update been clicked
    if (isset($_POST['update'])) {
        // if the title and content inputs have values
        if( (isset($_POST['title']) && isset($_POST['content']) )  ){
            // contain the new title updated in variables
            $title_new = $_POST['title'];
            $content_new = $_POST['content'];
            // pre-process entered string from the new content to ensure all texts only
            $content_new = $db->real_escape_string($content_new);

            // update query
            $update = "UPDATE blogs" . 
                      " SET title='{$title_new}', content='{$content_new}', datetime='{$today}'" . 
                      " WHERE id='{$id_num}'";
            // ensure both inputs are not empty
            if( strlen($title_new) > 0 && strlen($content_new) > 0 ){
                // execute the query
                $result_update = $db->query($update);
                // redirect to the index
                header('Location: index.php');
                exit;
            }
            else{
                // if it fails, redirect to an error message generated by php
                header('Location: error.php');
                exit;
            }
        }
    } // if the delete button has been clicked
    elseif (isset($_POST['delete'])) {
        // only execute the delete query if the user clicks ok and redirect
        // to the index page
        if($confirm_box){
            $result_del = $db->query($delete_query);

            header('Location: index.php');
            exit;
        }
    }
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <title>Blog - Editing on <?= $title ?></title>
    <link rel="stylesheet" href="styles.css" type="text/css" />
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <h1><a href="index.php">Blog - Edit Post</a></h1>

            <?php include 'constants/search.php'; ?>

        </div> 
		
        <?php include 'constants/navigation.php'; ?>
        
        <form method="post" action="">
            <fieldset>
                <legend>Edit Blog Post</legend>
                <p>
                    Title: 
                    <br />
                    <!-- input text box's value contains the row's title -->
                    <input id="title" name="title" type="text" value='<?= $title ?>' size="40" style="background-color: white"/>
                </p>
                <p>
                    Content: 
                    <br />
                    <!-- textarea's value contains the row's content -->
                    <textarea id="content" name="content" rows="10" cols="50" style="background-color: white"><?= $content ?></textarea>
                </p>
                <p> 
                    <input type="submit" name="update" value="Update" style="background-color: white" />
                    <!-- include an onclick to return a value for confirmation defined in the 
                         php block -->
                    <input type="submit" name="delete" value="Delete" onclick="return <?= $confirm_box ?>" style="background-color: white" /> 
                </p>
            </fieldset>
        </form>
        <div id="footer">
            <h5>Copywrong <?= date('Y') ?> - Every Rights</h5>
        </div> 
	</div>
</body>
</html>